default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 20
  timeout: 5000

development:
  <<: *default
  database: awesome_conf_api_development

test:
  <<: *default
  database: awesome_conf_api_test

production:
  <<: *default
  database:
